/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.Contacto;
import Controller.GestorContactos;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumno
 */
public class FrmListar extends javax.swing.JFrame {
     
    /**
     * Creates new form FrmListar
     */
    public FrmListar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        refresh();
    }

    List<Contacto> listaTodos;
    public void refresh(){ // Method to refresh the Jtable
        
        listaTodos = new GestorContactos().listarTodos();
        
        DefaultTableModel mTabla = new DefaultTableModel();
        mTabla.setColumnIdentifiers(new String[]{"Nombre","Apellido","Direccion","Fecha de Nacimiento","Telefono"});
        for (Contacto c: listaTodos){
            mTabla.addRow(new Object[]{c.getNombre(),c.getApellido(),c.getDireccion(),c.getFechaNacimiento(),c.getTelefonosCollection().stream().findFirst()});
        }
        tblListaTodos.setModel(mTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaTodos = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Contactos");

        tblListaTodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaTodos);

        btnActualizar.setText("Editar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
//        int valor = tblListaTodos.getSelectedRow();
//        System.out.println(valor);
        
//        DefaultTableModel mTabla = new DefaultTableModel();
//        mTabla.getDataVector().elementAt(tblListaTodos.getSelectedRow());
        
//        Object obj = new Object();
//        obj = mTabla.getDataVector().elementAt(tblListaTodos.getSelectedRow());
//        obj = mTabla.getValueAt(tblListaTodos.getSelectedRow(), tblListaTodos.getSelectedColumn());
//        
//        
//        List<Contacto> cont = new ArrayList<>();
//        
//        System.out.println(obj);

        Contacto c = listaTodos.get(tblListaTodos.getSelectedRow());
        
        FrmActualizar ag3 = new FrmActualizar(c);
        ag3.setVisible(true);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        //DefaultTableModel mTabla = new DefaultTableModel();
        
        int fila = tblListaTodos.getSelectedRow();
        //System.out.println(fila);
        //int valor = (int) tblListaTodos.getModel().getValueAt(fila, 0);
        Contacto c = listaTodos.get(tblListaTodos.getSelectedRow());
        
        new GestorContactos().borrar(c.getIdContacto());
        refresh();
        
        // Heredar AbstractTableModel (Crear una clase ContactosTableModel)
        // Sobreescribir
        //  getRowCount() : int
        //  getColumnCount() : int
        //  getColumnName(int c) : String
        //  getValueAt(int f, int c): Object
        
        //Poly requiere: Puntero a la clase base y sobreescritura
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaTodos;
    // End of variables declaration//GEN-END:variables
}
